services:
  db:
    image: postgres:16.4
    restart: always
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kanban
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:
